# Pod using Secret as environment variables
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.28
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
  restartPolicy: Never
---
# Pod using Secret as volume
apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.28
      command: ["/bin/sh", "-c", "ls /etc/db-credentials; sleep 3600"]
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/db-credentials
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: db-credentials
  restartPolicy: Never