apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  # Environment variables
  NGINX_HOST: example.com
  NGINX_PORT: "80"
  
  # Configuration file
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Custom configuration from ConfigMap
        location /config {
            return 200 'ConfigMap is working!';
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }