apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Values must be base64 encoded
  # echo -n 'myusername' | base64
  # echo -n 'mypassword' | base64
  DB_USER: bXl1c2VybmFtZQ==  # myusername
  DB_PASS: bXlwYXNzd29yZA==  # mypassword