apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
data:
  message: {{ .Values.config.message | quote }}
  color: {{ .Values.config.color | quote }}