apiVersion: v1
kind: Namespace
metadata:
  name: resource-demo
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: resource-demo
spec:
  hard:
    # Pod count limit
    pods: "5"
    # CPU limits
    requests.cpu: "1"
    limits.cpu: "2"
    # Memory limits
    requests.memory: 1Gi
    limits.memory: 2Gi
    # Storage limits
    requests.storage: 5Gi
    # PVC count limit
    persistentvolumeclaims: "5"
    # Service limits
    services: "5"
    services.nodeports: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: resource-demo
spec:
  limits:
  - type: Container
    default:
      # Default limits if not specified
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      # Default requests if not specified
      cpu: 100m
      memory: 128Mi
    max:
      # Maximum allowed
      cpu: 500m
      memory: 512Mi
    min:
      # Minimum allowed
      cpu: 50m
      memory: 64Mi