apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  concurrencyPolicy: Forbid  # Don't allow concurrent jobs
  successfulJobsHistoryLimit: 3  # Keep history of 3 successful jobs
  failedJobsHistoryLimit: 1  # Keep history of 1 failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command: ['sh', '-c', 'echo "Hello from the Kubernetes CronJob! Current time: $(date)" && sleep 5']
          restartPolicy: OnFailure